name: Deploy NODE-CHAT-SERVER to Amazon ECR

on:
  workflow_call:
    inputs:
      application_name:
        required: true
        type: string
      environment_name:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node.js version 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'

      - name: Generate deployment package
        run: |
            yarn install
            zip -r deploy.zip .
          
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}     # github secrets로 등록한 값 사용
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # github secrets로 등록한 값 사용
          application_name: ${{ inputs.application_name }}    # EB application 이름1
          environment_name: ${{ inputs.environment_name }}    # EB environment 이름
          version_label: ${{ github.run_number }}
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip
